language: go
go:
  - "1.12"
  - tip

go_import_path: k8s.io/gengo

jobs:
  include:
    - stage: Run tests
      script:
        - find . -name vendor -prune -o -name Makefile -print | xargs -I% sh -c 'make -C $(dirname %) test'
        - GO111MODULE=on go test -v ./...
    - stage: Verify examples
      script:
        - GO111MODULE=on go run ./examples/import-boss/main.go -i $(go list k8s.io/gengo/...) --verify-only
